[package]
name = "rustc_codegen_qir"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["dylib"]

[dependencies]

[package.metadata.rust-analyzer]
# This crate uses #[feature(rustc_private)]
rustc_private = true
